AWSTemplateFormatVersion: '2010-09-09'
Description: Template for creating Auto Scaling Group
Parameters:
  ClusterName:
    Description: The ECS Cluster Name
    Type: String
  Subnets:
    Description: List of subnets for the ECS Instances
    Type: 'List<AWS::EC2::Subnet::Id>'
  LaunchConfigurationName:
    Type: String
    Description: Enter LaunchConfiguration Name
  Cooldown:
    Type: String
    Default: 30
    Description: Enter ELB Name
  DesiredCapacity:
    Type: String
    Default: 1
    Description: Enter ELB Name
  MinSize:
    Type: String
    Default: 1
    Description: Enter ELB Name
  MaxSize:
    Type: String
    Default: 2
    Description: Enter ELB Name
  HealthCheckGracePeriod:
    Type: String
    Default: 50
    Description: Enter ELB Name
  HealthCheckType:
    Type: String
    Default: EC2
    Description: Enter ELB Name

Resources:
  ESSAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      Cooldown:                !Ref Cooldown
      DesiredCapacity:         !Ref DesiredCapacity
      MinSize:                 !Ref MinSize
      MaxSize:                 !Ref MaxSize
      HealthCheckGracePeriod:  !Ref HealthCheckGracePeriod
      HealthCheckType:         !Ref HealthCheckType
      LaunchConfigurationName: !Ref LaunchConfigurationName
      MetricsCollection:
        - Granularity: 1Minute
      VPCZoneIdentifier:       !Ref Subnets
      Tags:
        - PropagateAtLaunch: 'true'
          Key: Name
          Value:
            'Fn::Join':
              - '-'
              - - Ref: ClusterName
                - Node
        - PropagateAtLaunch: 'true'
          Key: ECS_Cluster
          Value: !Ref ClusterName
Outputs:
  ESSAutoScalingGroup:
    Value: !Ref ESSAutoScalingGroup
    Description: ESS Autoscaling Group
